services:
  bookmark-reverb:
    build:
      context: .
    environment:
      PHP_OPCACHE_ENABLE: 1
      AUTORUN_ENABLED: true
      LOG_CHANNEL: stderr
      AUTORUN_LARAVEL_MIGRATION_ISOLATION: false
      AUTORUN_LARAVEL_MIGRATION: false
    command: [ "php", "/var/www/html/artisan", "--port=8000", "reverb:start" ]
    stop_signal: SIGTERM
    healthcheck:
      test: [ "CMD", "healthcheck-reverb" ]
      start_period: 10s
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"

volumes:
  storage_private:
  storage_public:
  storage_sessions:
  storage_logs:
