services:
  php:
    build:
      context: .
      args:
        VITE_REVERB_APP_KEY: ktlkhaldrwqhdlh1qx9h
    environment:
      PHP_OPCACHE_ENABLE: 1
      AUTORUN_ENABLED: true
      VITE_REVERB_APP_KEY: ktlkhaldrwqhdlh1qx9h
      VITE_REVERB_HOST: ${VITE_REVERB_HOST}
      VITE_REVERB_PORT: ${VITE_REVERB_PORT}
      VITE_REVERB_SCHEME: ${VITE_REVERB_SCHEME}
      APP_URL: ${APP_URL}

    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"

volumes:
  certificates:
  storage_private:
  storage_public:
  storage_sessions:
  storage_logs:
