services:
  php:
    build:
      context: .
      args:
        VITE_REVERB_APP_KEY: ${VITE_REVERB_APP_KEY}
        VITE_REVERB_HOST: ${VITE_REVERB_HOST}
        APP_URL: ${APP_URL}
    environment:
      PHP_OPCACHE_ENABLE: 1
      AUTORUN_ENABLED: true


    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"

volumes:
  certificates:
  storage_private:
  storage_public:
  storage_sessions:
  storage_logs:
